title: Whimsical Doodles
email: felix@whimsicaldoodles.com
description: >
  Whimsical Doodles is a technology consultancy based in London, thoughts on
  Ruby, the web and technology.
twitter: wwwhimsydoodle
github:  Whimsical-Doodles

markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
